### ISSUE TITLE
Error on require()

### ISSUE THREAD

**Issue by BoldCom** [austinpray/asset-builder#28]
Hi there!
I think I follow all the install instructions to start working with this plugin in my new project, but when I did the require declaration throw me the following error:

```
undefined:7
  },
  ^
SyntaxError: Unexpected token }
    at Object.parse (native)
    at module.exports (/Users/username/Dropbox/www/newproject/node_modules/asset-builder/lib/readManifest.js:19:15)
    at new module.exports (/Users/username/Dropbox/www/newproject/node_modules/asset-builder/lib/Manifest.js:28:34)
    at module.exports (/Users/username/Dropbox/www/newproject/node_modules/asset-builder/index.js:17:10)
    at Object.<anonymous> (/Users/username/Dropbox/www/newproject/gulpfile.js:2:40)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
And there is my gulpfile.js
```javascript
var gulp             = require('gulp'),
    gulpLoadPlugins  = require('gulp-load-plugins'),
    $                =  gulpLoadPlugins();
    
var manifest = require('asset-builder')('./assets/manifest.json');
```
When I delete the manifest line gulp run as usual but when i add that line throw me that error.
What I am missing here?

**Comment by retlehs** [comment]
your manifest.json file probably has a syntax error

**Comment by BoldCom** [comment]
ups!Yes! I really had a error in my manifest.json file. Thanks for the help!
